if (NEBULA_PEDANTIC_WARNINGS)
    if (NEBULA_COMPILER STREQUAL "CLANG" OR NEBULA_COMPILE STREQUAL "GCC")
        set(NEBULA_COMPILER_OPTIONS -Wall -Wextra -Wpedantic -Werror)
    elseif (MSVC)
        set(NEBULA_COMPILER_OPTIONS /W4 /WX)
    else()
        set(NEBULA_COMPILER_OPTIONS)
        message(WARNING "Unknown compiler, can't enable warnings")
    endif()
endif()

function(nebula_target target)
    target_compile_options(${target} PUBLIC "${NEBULA_COMPILER_FLAGS}")
endfunction()
